### ISSUE TITLE
Add VA certificates as SSL trust anchor inside docker image

### ISSUE THREAD

**Issue by ffafara-tw** [department-of-veterans-affairs/notification-api#113]
**As** a VANotify system owner
**I want** VANotify to communicate with external providers like Granicus or Twilio over encrypted connections
**So that** data is secured during transit.

# Context
- All traffic from VA network going out to internet is decrypted, inspected and encrypted on as it passes through Trusted Internet Connection (basically VA is doing Man in the middle attack).
- We need to add VA certificates to our docker images, so that they can communicate with the internet over SSL.

# Acceptance Criteria
- [ ] python flask trusts VA ssl certs and can communicate over ssl with hosts on the internet (granicus, twilio, etc.)
- [ ] traffic that uses python `requests` package trusts VA ssl certs
- [ ] linux system trusts VA ssl certs (curl, wget, etc.)

**We'll know if it's not working if:**
We see errors when trying to deliver emails with Granicus, probably SSL failures.

# Tasks

- [ ] Get VA certs from http://crl.pki.va.gov/PKI/AIA/VA/ (only accessible by CAG or GFE)
  - [ ] Ask someone on platform support which certificates we'll need
  - [ ] Or have a look in the `devops` repo to see if they're in there
  - [ ] Or in the `Dockerfile` of `vets-api`
- [ ] Commit VA certs to notification-api repo (don't worry, they're public)
- [ ] Follow steps in below comment:
  - [ ] trust certificates for linux
  - [ ] trust certificates for `requests`

# Notes
- Need VA Environment to test
  - could test by starting an EC2 with docker inside VA env, and seeing if we can `curl`
  - or by writing a small python script that uses `requests`

**Comment by ffafara-tw** [comment]
**Dev analysis:**
- To install certificates in alpine linux system trust it should be enough to add:
```
RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
COPY ./mycert.crt /usr/local/share/ca-certificates/mycert.crt
RUN update-ca-certificates
```
to our docker file

- For some of outgoing connections we use requests package which uses it's own certificate trust chain that comes from certifi package and contains Mozilla trust store.
To provide custom CA certificates we should try to use REQUESTS_CA_BUNDLE environment variable.
Please follow steps described in:
https://requests.readthedocs.io/en/master/user/advanced/#ssl-cert-verification

- VA certificates can be found here: http://crl.pki.va.gov/PKI/AIA/VA/

**Comment by lingtran** [comment]
Need to convert from .cer to .crt, run this command:
`openssl x509 -inform der -in {cer file} -out {crt file}`

Certificate used: `VA-Internal-S2-RCA1-v1.cer'

Ran `docker run -it {image} /bin/bash` and verified that the env var for REQUESTS_CA_BUNDLE is correct. Also verified that the bundled ca-certificates.crt also exists and contains the VA certificate we added/copied over.

Within docker container, we used the python interpreter to make requests with the requests library. We were not able to verify the cert path explicitly, but were able to get 200 responses which implies that perhaps the SSL certificate may have been picked up. We did not get any errors such as `requests.exceptions.SSLError`.
