### ISSUE TITLE
Spike: Investigate issue with three tables and associated API routes.

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1200]
## User Story - Business Goal
Technical investigation into TemplateBase and ServiceSmsSender and Notification is necessary to better understand the code, which enables better iteration and modifications. This is tech debt. 

### User Story(ies)
**As a** VANotify engineer, client and QA
**I want** to understand/fix the API routes for creating and updating sms senders and templates
**So that** developing and testing against the service is a better experience.

### Additional Info and Resources
**Templates:**
- Any sms template created is populated with a property `reply_to_text` set to the phone number of the default `sms_sender_id`. This makes no sense, because there may be multiple sms_sender_id objects in a service and any 'reply-to' should be set to the `sms_sender_id `used to send the template. 
- Also, it is unclear how or why this property would even be used, given that when you receive a text from a phone number, you would be replying to that phone number.  
- Last, the property cannot be modified to null or to a different `sms_sender_id` using the POST `{{notification-api-url}}/service/{{service-id}}/template/{{template_id}}` route

**ServiceSmsSender**
- includes a column for `reply_to_text` in the table but there's a "serialize" method, and it doesn't include `reply_to_text`.
- ~~ Once an SMS sender is added to a new service and set as the default, any new SMS sender cannot be set to the default without directly modifying the database. The POST update `{{notification-api-url}}/service/{{service-id}}/sms-sender/{{sms-sender-id}}` is unable to change the default sms sender from true to false, doing so causes an error. The workaround is currently just to change the number associated with the default object.~~ This actually works. Confirmed in DEV and with Cris

** Notifications **
> It could definitely use a clean-up.  If nothing else, I would like to rename some columns to make their purposes more explicit.  Notification instances have "to" (recipient, I think), "sent_by" (a string), "sms_sender" (from phone number, I think), and "reply_to_text" (nullable; maybe only for e-mail?).

## Acceptance Criteria & Checklist
_**Required**_

- [x] Determine how and why `reply_to_text` is included in the template object, create a ticket to remove if unneeded
- [x] Determine how and why `reply_to_text` is automatically set to the default `sms_sender_id` on the service; if needed, create a ticket to modify this behavior based on investigation
- [x] Determine how and why `reply_to_text` cannot be set to null or another `sms_sender_id`; if needed,create a ticket to modify this behavior based on investigation
- [x] Determine if `reply_to_text` is needed in the sms sender object; create a ticket to modify if so.'
- [x] Determine how configuring default sms senders should work and create tickets needed to fix the behavior of the POST update route.
- [ ] Determine next steps for cleaning up Notification and create a ticket.
- [x] Technical Documentation has been created and linked in the [Wiki](https://github.com/department-of-veterans-affairs/notification-api/wiki)
- [x] Learnings have been shared with the team, and decisions have been documented
- [x] Tickets for next steps have been identified and created; tickets to include updating swagger for any routes touched.

Completed research addresses the problems and/or answers the questions below:  

- What does the reply_to_text field do in various tables and what should it do?
- How should updating an sms sender to be a default work?
- How do these three tables interact with each other?

## Timebox
_Leave blank if n/a_

**Comment by k-macmillan** [comment]
Leaving for now.

**Comment by MackHalliday** [comment]
##TODO 

- Determine how and why reply_to_text is included in the template object, create a ticket to remove if unneeded

- Determine how and why reply_to_text is automatically set to the default sms_sender_id on the service; if needed, create a ticket to modify this behavior based on investigation

- Determine how and why reply_to_text cannot be set to null or another sms_sender_id; if needed,create a ticket to modify this behavior based on investigation

- Determine if reply_to_text is needed in the sms sender object; create a ticket to modify if so.'

- Determine how configuring default sms senders should work and create tickets needed to fix the behavior of the POST update route.

- Determine next steps for cleaning up Notification and create a ticket.

- Technical Documentation has been created and linked in the [Wiki](https://github.com/department-of-veterans-affairs/notification-api/wiki)

- Learnings have been shared with the team, and decisions have been documented

- Tickets for next steps have been identified and created; tickets to include updating swagger for any routes touched.

**Comment by MackHalliday** [comment]
I see where this non-sense is happening but not sure what can be gutted yet.

**Comment by MackHalliday** [comment]
"Once an SMS sender is added to a new service and set as the default, any new SMS sender cannot be set to the default without directly modifying the database. The POST update {{notification-api-url}}/service/{{service-id}}/sms-sender/{{sms-sender-id}} is unable to change the default sms sender from true to false, doing so causes an error. The workaround is currently just to change the number associated with the default object." 

This does not seem to be an issue - I was able to test in DEV.  I created two active SMSsender. One was the default, and then I prompted the second one to the default. The original default was then automatically set to `is_default` false

**Comment by MackHalliday** [comment]
## Tables in question

<img width="870" alt="Image" src="https://github.com/user-attachments/assets/574e5be3-0349-42e6-93c7-1d541b723cd3" />

<img width="895" alt="Image" src="https://github.com/user-attachments/assets/672ae834-5211-4b23-9507-3b1468494b86" />

<img width="838" alt="Image" src="https://github.com/user-attachments/assets/62abc700-e23a-438f-a0c5-9343182e3c20" />

**Comment by MackHalliday** [comment]
Look into 
https://github.com/orgs/department-of-veterans-affairs/projects/1417/views/1?filterQuery=&pane=issue&itemId=94080624&issue=department-of-veterans-affairs%7Cnotification-api%7C2253

**Comment by npmartin-oddball** [comment]
Ticket is rolling over to our next sprint (Sprint 21), per @MackHalliday's comment above.
