### ISSUE TITLE
Implement Datadog Version Tracking for Deployment Insights

### ISSUE THREAD

**Issue by ldraney** [department-of-veterans-affairs/notification-api#1374]
## User Story - Business Need

The value of version tracking is that with each deployment we will be able to automatically detect anomalous errors or metrics between version of our application.  This will also prove useful to track/prove application adjustments intended for scalability and reliability.

In anticipation of upcoming enhancements to our application, implementation of version deployment tracking in Datadog is a priority, especially in regard to scalability and reliability. This carries great value as it enables rapid and effective assessment of the impact of our upgrades. By comparing the metrics with those of previous versions, we can accurately determine whether these improvements are introducing new errors or reducing them.  Datadog automatically begins detecting anomalies between versions via Watchdog, but it takes time for it to get a history of our application, which will only begin once we have implemented this; thus its important to implement this asap.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Engineer and Product stakeholder 
**I want** to set up Datadog deployment tracking for our ECS Fargate setup
**So that** I can monitor, analyze, and detect anomalies in the metrics and logs between different versions of our application

### Additional Info and Resources
[This Datadog Blog](https://www.datadoghq.com/blog/unified-service-tagging/) explains how `DD_VERSION` sets [the version label](https://docs.datadoghq.com/tracing/services/deployment_tracking/) in Datadog, which is used in deployment tracking.  

Context:
Our ECS Fargate setup is configured via environment variables in our task definitions. 
The trick of this will likely be in how we are able to dynamically update the DD_VERSION env variable.
Adding DD_VERSION is enough to get version tracking to work; but the trick is to dynamically update this value.  This may involve using something other than the task_definition variables.  If implementing a solution proves more complex, then creating a SPIKE will be necessary. 

The below resources as a refresher on our ecs setup (via `ddtrace-run` and ENV variables):
- [Datadog AWS Fargate Monitoring](https://www.datadoghq.com/blog/aws-fargate-monitoring-with-datadog/)
- [Integrating Datadog Agent in ECS Fargate](https://dev.to/aws-builders/how-to-integrate-datadog-agent-in-ecs-fargate-4cli)
- [Monitor ECS Applications on AWS Fargate With Datadog](https://blog.iron.io/monitor-ecs-applications-on-aws-fargate-with-datadog/)

Here is documentation specific to [Deployment Tracking](https://docs.datadoghq.com/tracing/services/deployment_tracking/)

## Engineering Checklist
- [ ] Ensure the Datadog image in ecr and dependency have been updated as necessary
- [ ] Confirm with the team the versioning strategy before implementing beyond dev
- [ ] Contact ddog team to ask how to dynamically update the DD_VERSION variable
- [ ] Find examples online of similar situations and how they were resolved (our fargate-ecs + github Actions is the peculiarity to our setup)
- [ ] Experiment with methods to update DD_VERSION via application.py, task_definition, or some other potential solution. Record attempts in comments of this ticket.
- [ ] Determine how to test/prove that version is being successfully updated; hopefully just appearing in the apm dashboard is sufficient.
- [ ] Apply update for all environments, or make subsequent ticket, if necessary

## Acceptance Criteria
- dd_version successfully shows up on the apm dashboard:
- determine that dd_version successfully showing up in apm dashboard is sufficient as a POC

## Potential Dependencies
- Access to AWS Fargate and Datadog accounts

## Potential Solution:
1. Store DD_VERSION as an AWS SSM parameter
2. Use that parameter in the task definition for each environment
3. Update that parameter in deployment.yml, in a step before `Render migration task definition`, where it updates SSM according to the latest version of our Github repo.  
4. Make sure that every environment uses this value, and can clearly be distinguished by environment in the datadog APM dashboard. 

Kyle's input: Possibly utilizing the year_revision to set the version for datadog. We should be able to pluck that information from aws with the CLI in our Action.

**Comment by mjones-oddball** [comment]
@ldraney Got a question from @cris-oddball "Is this tracking our app version, or some version of Datadog?  If we are tracking the app version, I don't think the env var should be DD_VERSION? We have releases that are versioned, shouldn't we leverage something about that?"

**Comment by ldraney** [comment]
I added this comment to the additional resources:
[This Datadog Blog](https://www.datadoghq.com/blog/unified-service-tagging/) explains how `DD_VERSION` sets [the version label](https://docs.datadoghq.com/tracing/services/deployment_tracking/) in Datadog, which is used in deployment tracking.

**Comment by cris-oddball** [comment]
Based on the blog, this looks the service of our API service. We only 'version' (in the real sense of the word) when we deploy to staging and prod (example: v1.6.6) and Infra is versioned separately (but we would want to see that, too, in DD).

I think as a team we need to discuss what this looks like or turn this into a Spike to decide which way to do this.

Examples:
- do we just track the tag version for releases?  (ex 1.6.6)
- or do we track the tags I cut to send things to perf?  (ex v1.6.6-1035-some-feature)
- we don't version anything when we deploy to dev right now, will that change?

@k-macmillan @mjones-oddball @ldraney

**Comment by k-macmillan** [comment]
I'd like to automate it. Possibly utilizing the `year_revision` to set the version for datadog. We should be able to pluck that information from aws with the [CLI](https://docs.aws.amazon.com/cli/latest/reference/ecs/describe-task-definition.html) in our Action.

**Comment by mjones-oddball** [comment]
Keeping ticket as is based on Kyle's feedback above

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1374?planning-poker) with Zenhub @cris-oddball @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov @EvanParish

**Comment by mchlwellman** [comment]
This might be a way to test before deploying - [ddtrace integration testing](https://ddtrace.readthedocs.io/en/stable/contributing-integrations.html#what-are-snapshot-tests). I'm not sure if DD_VERSION appears but it seems like it should.
