### ISSUE TITLE
Spike: review TIME for scheduled_for and determine how to improve it

### ISSUE THREAD

**Issue by cris-oddball** [department-of-veterans-affairs/notification-api#1439]
## User Story - Business Goal

The v2 and v3 notification routes have a `scheduled_for` property (a permission that must be added to any service that wishes to use it) that can be sent in the POST payload. Testing has revealed that the routes do send scheduled emails and sms however there is a time factor that must be addressed.

Note that v3 implementation is partial and is also different than the v2 implementation. Review both to determine what changes need to be made to each and create appropriate tickets.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VANotify 
**I want** to spruce up the notifications scheduled_for feature 
**So that** I can provide that functionality to clients

### Additional Info and Resources

- Read the [investigation and testing document ](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/Quality%20Assurance/scheduling%20_notificatiions.md)created by QA
- The earliest a notification can be sent is 7 hours from present (at least when testing in MDT, which is UTC-6); this will of course vary by what time zone you are in. For the east coast, the earliest a notification could be sent is 5 hours from the present. 
- The property expects a value in this format: "2023-09-06 17:00" or `%Y-%m-%d %H:%M`, based on the code. 
- This time must be in UTC. If you try to any US time zone's time, you will get an error stating that `scheduled_for` cannot be in the past (because our offset is behind UTC, maybe this feature works as expected in Ukraine). 
- You can't pass along your TZ with that format.
- Once created, the `scheduled_for` value in the GET response is not the value you sent, but 8 hours in the future.
- Based on the `scheduled_for` value in the GET response, the notification is actually received 4 hours earlier than that (but 4 hours later than what the `scheduled_for` value was in the POST request.  See  [Testing Doc](https://github.com/department-of-veterans-affairs/vanotify-team/blob/master/Engineering/Quality%20Assurance/scheduling%20_notificatiions.md)
- The application appears to use "America/New York" as its timezone while the DB uses UTC., which may be a factor here.

## Acceptance Criteria & Checklist

- [ ] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  

1. We understand how Scheduled feature works and how to improve it for our clients.
2. Determine if it is valuable for the client to be able to send along a TZ in the timestamp. The code appears to do a conversion, so the value might be sent in this format:` %Y-%m-%dT%H:%M:%S.%fZ`
3. If that is not valuable for the client and we inform the clients that the TZ they send must be in UTC, then the insertion into the DB must be the value that was sent, not a value that adds any amount of time to it.
4. Determine if it makes more sense for the app and the DB to be in the same timezone (and what impact, if any, the current state has on billing data)

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1439?planning-poker) with Zenhub @k-macmillan @kalbfled @MackHalliday @mchlwellman @EvanParish @cris-oddball @coreycarvalho

**Comment by cris-oddball** [comment]
@mjones-oddball will do, on my todo list!

**Comment by cris-oddball** [comment]
Testing doc added to team repo and linked in description.

**Comment by npmartin-oddball** [comment]
Still broken/still needed.

**Comment by Scott-S** [comment]
## Meeting notes

- are we going to send at **exactly** the time scheduled? We make a best effort to send at that time. We'll send at that time or later, no earlier?
  - what's a simple way to implement this as a first pass? ie, no more than X notifications for Y service (in period Z?)
  - metric/visual of scheduled notifications for monitoring?
  - put it in the non-priority worker pool
- does vets-api support this `scheduled_for` feature (ie, the gem that portal maintains)?

### Rate Limiting
- We may need to impose limits/bucketing/queuing (what if everyone schedules at once?). This should tie into the existing rate limiting discussion [here](https://github.com/department-of-veterans-affairs/vanotify-team/wiki/rate-limiting-2625) and [here](https://github.com/department-of-veterans-affairs/vanotify-team/issues/1958)
- This should be built in a way to be checking for both these scheduled_for and real-time (the goal is to not have to take any special measure for this)

## TODOs
- is there currently a limit to how far out notifications can be scheduled?
- Can anyone use this right now?
  - look into this `Added the schedule_notifications permission to the "VANotify QA Automation" in Dev`
  - no scheduled notifications permissions currently in prod
- add spike ticket: https://github.com/department-of-veterans-affairs/vanotify-team/tree/main/Engineering/SPIKES
- add epic and put all these tickets and this spike in the epic. This will be for ENP

**Comment by Scott-S** [comment]
Added notes to wiki: https://github.com/department-of-veterans-affairs/vanotify-team/wiki/Scheduled-Notifications-%E2%80%90-1439

Also see Epic [#2049](https://github.com/department-of-veterans-affairs/vanotify-team/issues/2049)
