### ISSUE TITLE
GA4 Migration: Build dynamic URL for open email tracking

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1847]
## User Story - Business Need

We need to construct a dynamic URL that contains information on notification emails being sent. This URL should be passed as an optional parameter into the HTMLEmailTemplate class within the send_email_to_provider method. The HTMLEmailTemplate class is located in the notification-utils repository. In an earlier user story, a dynamic URL variable was embedded in the notification email, and, when the variable is populated and the email is openned, a GET request will be made to our `notification-api` repo. This user story focuses exclusively on building and passing the dynamic GET URL to the HTMLEmailTemplate class.

FIX BUG created in [#153](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-utils/153). We need to update the new GET `ga4/open-email-tracking` to return an pixel to avoid the broken image icon in appearing in emails. 

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a VA Notify** Developer
**I want** to build a dynamic URL that contains information on emails being sent
**So that** the dynamic URL can eventually be use to execute a GET request through pixel tracking when the email is opened. 

### Additional Info and Resources
- [Implementation and Ticket Overview](https://docs.google.com/presentation/d/1BKOQQyxlUsE08Z7mKhzWmUZmnsxKKU_NVCHJiUEgY58/edit?usp=sharing)
- **Background on Email Tracking**: We currently use UA to track email opens via pixel tracking. GA4 does not support pixel tracking directly. Instead, we will embed a dynamic URL in the email that sends a GET request to our application when the email is opened. This GET request will then trigger a POST request to GA4 with the necessary data.
- Jamie Stutt on dsva.slack.com, but please ask @MackHalliday first as she has already talked to her and does not want to ask Jamie the same questions.
- [Campaign Details GA4 fields](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events#campaign_details)

## Engineering Checklist
- [x] Poetry update for changes to `notification-utils` made in [UTILS-855](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-infra/855)
- [x]  Create methods to build the new dynamic URL in the `app.googleanalytics` folder 
  - **URL**
      ```
       url = (
           f'{public_application_root}/ga4/open-email-tracking?'
           f'campaign={notification.template.name}&campaign_id={notification.template.id}&'
           f'name=email_opens&source=vanotify&medium=email&'
           f'content={notification.service.name}/{notification.service.id}/{notification.id}'
       )
      ```
- [x] Call the new method in place of the UA implementation (`gapixels.build_ga_pixel_url`) in the `get_html_email_options`. Add the value for the dynamic URL to the html email options.
- [x] Remove any UA implementation code 
- [x] Log the dynamic URL so the values appear in DataDog
- [x] Add Documentation to VANotify Team
- [x] Fix bug for broken image icon appearing in emails by returning pixel image from GET `ga4/open-email-tracking` 

## Acceptance Criteria

- The new dynamic URL can be passed into the HTMLEmailTemplate as part of an optional arg
- A GET request is made to the `notification-api` repo (The POST request to GA4 may not be fully implemented at this time)
- Should work with emails that do and do not allow images to load. If not allowed, then email tracking should not be sent.
- Fix bug: No broken image icon in email 

## QA Considerations
- A GET request is made to the `notification-api` repo (The `notification-api` GET endpoint to trigger POST to GA4 may not be fully implemented at this time)

**Comment by cris-oddball** [comment]
Adding the QA Reviewed label, but the QA work on this ticket seems incomplete (based on the [Utils ticket ](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/notification-utils/153)saying that the QA info will be on this ticket. We can discuss in Refinement or during the QA convo when the developer picks up the ticket.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1847?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by MackHalliday** [comment]
Yesterday 
- Met with QA 
- Remove old code 
- Added new method for URL 

Today 
- Update unit testing 
- Test in DEV

**Comment by MackHalliday** [comment]
Yesterday 
- Complete unit testing 
- Running into issues with running pytest Locally.

**Comment by MackHalliday** [comment]
Friday 
- Testing on DEV 
- Issues with dynamic URL being shown as cache GMAIL url (ci3.googleusercontent). 

Today 
- Figured out issues with dynamic URL with QA this morning. Need to wait 1 minute to open email due to cache. And making adjustments to URL. 
- Open PR

**Comment by MackHalliday** [comment]
Yesterday 
- PR up and reviewed. 
- Create documentation for GA4 pixel tracking 
- Crated new bug ticket for broken icon 

Today 
- Update code based on feedback from PR

**Comment by MackHalliday** [comment]
Yesterday 
- Update `ga4/open-email-tracking` to return a pixel image 
- Update code based on feedback from PR 
- Updating testing based on changes above 

Today 
- Continue to fix tests. Running into Runtime issues 
- Retest in DEV and reopen PR for review

**Comment by MackHalliday** [comment]
Blocked
Yesterday 
- PR reviewed and working in DEV 
- Local testing working 
- Running into issue with DEV test suite running in Github Workflow 

Basically, GitHub Workflow tests do not run in a Docker Container. So when the tests hit the `ga4/open-email-tracking` endpoint, the image is under a different path than in a local env or the DEV env.

**Comment by cris-oddball** [comment]
`QA TESTING IN PROGRESS`

-[ ]  Happy Path - email sent without being opened - tested by regression - 200 is returned

> INFO 2024-07-18 18:16:50,781 /app/app/googleanalytics/ga4.py:33: b'campaign=hello_qa&campaign_id=37f1d6d2-1354-49bd-9600-2517e3fac79d&name=email_open&source=vanotify&medium=email&content=qatest/d44e841a-3d08-4f3d-9798-6e891cc4f585/5a395e3d-0d63-4c64-ba06-d919217058a1'

> 10.247.182.126 - - [18/Jul/2024:18:16:50 +0000] "GET /ga4/open-email-tracking?campaign=hello_qa&campaign_id=37f1d6d2-1354-49bd-9600-2517e3fac79d&name=email_open&source=vanotify&medium=email&content=qatest/d44e841a-3d08-4f3d-9798-6e891cc4f585/5a395e3d-0d63-4c64-ba06-d919217058a1 HTTP/1.1" 200 86 "-" "python-requests/2.32.3"



-[ ] Happy Path - email notification is sent and the email is opened, image blocking is ON, expect that the route is not hit
  - [ ] Gmail web Chrome
  - [ ] Gmail web Firefox
  - [ ] Gmail web Edge
  - [ ] Outlook client




-[ ] Happy Path - email notification is sent and the email is opened, image blocking is OFF, expect that the route is hit, a pixel is embedded
  - [ ] Gmail web Chrome
  - [ ] Gmail web Firefox
  - [ ] Gmail web Edge
  - [ ] Outlook client

**Comment by cris-oddball** [comment]
Holding open until Monday to remind me to deploy this to Prod.

**Comment by cris-oddball** [comment]
Deploying to Prod.
Need to create a new ticket prior to closing.
