### ISSUE TITLE
GA4 Migration: Trigger POST request to GA4 when open email tracking GET endpoint called

### ISSUE THREAD

**Issue by MackHalliday** [department-of-veterans-affairs/notification-api#1854]
## User Story - Business Need

We need to handle the extracted data from the open email tracking GET request, send a POST request to GA4 with the data, and ensure the POST request is executed in a Celery task. The developer will need to use an GA4 api-secret and a measurement-id for the POST request (These can be obtained from Kyle). These values should be environment variables and added to the task definitions. The Terraform in our vanotify-infra should already be updated with the GA4 environment variables.

We do not know exactly how to format the GA4 POST request. There will be a bit of discovery work in this ticket.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VA Notify Developer
**I want** to send a POST request to GA4 with the extracted data from the GET request in a Celery task
**So that** we can track email opens in GA4.

### Additional Info and Resources

-  [Implementation and Ticket Overview](https://docs.google.com/presentation/d/1BKOQQyxlUsE08Z7mKhzWmUZmnsxKKU_NVCHJiUEgY58/edit?usp=sharing)
- **Background on Email Tracking**: We currently use UA to track email opens via pixel tracking. GA4 does not support pixel tracking directly. Instead, we will embed a dynamic URL in the email that sends a GET request to our application when the email is opened. This GET request will then trigger a POST request to GA4 with the necessary data.
- Jamie Stutt on dsva.slack.com, but please ask @MackHalliday first as she has already talked to her and does not want to ask Jamie the same questions.
- [Campaign Details GA4 fields](https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events#campaign_details)

Potential code (Tweks to the POST request are necessary):

```
import os
from urllib.parse import urlencode
import requests
from flask import current_app, request
from celery import Celery

# Initialize Celery
celery = Celery(__name__)

@celery.task
def post_to_ga4(notification_id, template_name, template_id, service_id, service_name):
    # Build URL
    url_params_dict = {
        'measurement_id': os.environ['GOOGLE_ANALYTICS_MEASUREMENT_ID'],
        'api_secret': os.environ['GOOGLE_ANALYTICS_API_SECRET'],
    }
    url_str = current_app.config['GOOGLE_ANALYTICS_GA4_URL']
    url_params = urlencode(url_params_dict)
    url = f'{url_str}?{url_params}'

    content = f'{service_name}/{service_id}/{notification_id}'

    event_body = {
        "events": [{
            "name": "open_email",
            "params": {
                "campaign_id": template_id,
                "campaign": template_name,
                "source": "vanotify",
                "medium": "email",
                "content": content,
            }
        }]
    }

    response = requests.post(url, json=event_body)
    return response.status_code, response.json()

def handle_open_email_tracking():
    notification_id = request.args.get('notification_id')
    template_name = request.args.get('template_name')
    template_id = request.args.get('template_id')
    service_id = request.args.get('service_id')
    service_name = request.args.get('service_name')

    # Call the Celery task with the parsed parameters
    post_to_ga4.delay(notification_id, template_name, template_id, service_id, service_name)

    return "Email open tracked", 204
```

## Engineering Checklist
- [x] Determine the correct format for the GA4 POST request
- [x] Create a Celery task to handle the POST request to GA4 with simple retry functionality. 
- [x] Extract the values from the GET request and pass to POST request in Celery Tasks.
- [x]  Add any necessary error handling.
- [x]  Ensure api-secret and measurement-id are set as environment variables and added to the celery task definitions.

## Acceptance Criteria
- The GET request values are used in the POST request to GA4.
- POST requests to GA4 show up in the GA console
- The POST request to GA4 is executed within a Celery task.
- The necessary environment variables (api-secret and measurement-id) are added to the task definitions.

## QA Considerations
- Requests made to the new GET endpoint are successfully captured in GA4.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1854?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by mchlwellman** [comment]
Update: I have admin access to the analytics console, keys are created and I've tested the POST successfully. I have a celery task in place that I'm still testing. The plan today is to finish up the celery task and get going on the endpoint.

**Comment by mchlwellman** [comment]
I have the URL parameters

**Comment by mchlwellman** [comment]
Testing locally and events are displayed in the GA Email (staging) dashboard.  Next step is to deploy and test in the dev environment.

**Comment by mchlwellman** [comment]
There's two issues - 

- The Celery broker is not brokering the task. I am just running the task synchronously now to test.
- The new Celery task does not have access to the parameters created in the infra 855 ticket.

**Comment by cris-oddball** [comment]
PRs both approved and merged. Will send this up to Perf for testing.

Due to the late arrival to QA and the planning meeting today, this ticket cannot be closed out by EOD and will carry over to Tuesday, July 22, the new sprint to be closed after testing and deployments.

**Comment by cris-oddball** [comment]
**QA PASSED**

- [ ] When a notification email is opened, a GET request to our endpoint and a POST request is made to the googleanalytics endpoint.


Log chain of events:
```
[2024-07-22 20:45:30,980: DEBUG/ForkPoolWorker-4] Generated Google Analytics 4 pixel URL: https://sandbox-api.va.gov/vanotify/ga4/open-email-tracking?campaign=12.07test&campaign_id=65a7f39d-76df-4c57-9592-339e467d7b25&name=email_open&source=vanotify&medium=email&content=VA%20Notify/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/11fd3643-eea4-4e62-b8bd-478a35b117f4

10.247.182.99 - - [22/Jul/2024:20:48:48 +0000] "GET /ga4/open-email-tracking?campaign=12.07test&campaign_id=65a7f39d-76df-4c57-9592-339e467d7b25&name=email_open&source=vanotify&medium=email&content=VA%20Notify/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/11fd3643-eea4-4e62-b8bd-478a35b117f4 HTTP/1.1" 200 86 "-" "Mozilla/5.0 (Windows NT 5.1; rv:11.0) Gecko Firefox/11.0 (via ggpht.com GoogleImageProxy)"

[2024-07-22 20:48:48,184: INFO/ForkPoolWorker-4] GA4: post_to_ga4: notification_id: 11fd3643-eea4-4e62-b8bd-478a35b117f4, template_name: 12.07test, template_id: 65a7f39d-76df-4c57-9592-339e467d7b25, service_id: d6aa2c68-a2d9-4437-ab19-3ae8eb202553, service_name: VA Notify

[2024-07-22 20:48:48,185: DEBUG/ForkPoolWorker-4] Posting to GA4: {'client_id': 'vanotify', 'events': [{'name': 'email_open', 'params': {'campaign_id': '65a7f39d-76df-4c57-9592-339e467d7b25', 'campaign': '12.07test', 'source': 'vanotify', 'medium': 'email', 'content': 'VA Notify/d6aa2c68-a2d9-4437-ab19-3ae8eb202553/11fd3643-eea4-4e62-b8bd-478a35b117f4'}}]}

[2024-07-22 20:48:48,185: INFO/ForkPoolWorker-4] Posting event to GA4: email_open

[2024-07-22 20:48:48,367: DEBUG/ForkPoolWorker-4] GA4 response: 204

[2024-07-22 20:48:48,367: INFO/ForkPoolWorker-4] GA4 event email_open posted successfully
```


- [ ] Data is displayed in Google Analytics

<img width="325" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkg4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd6941be595be5d1014649ca2427ac1a8a15165b/Screenshot%202024-07-22%20at%202.53.31%E2%80%AFPM.jpg" alt="Screenshot 2024-07-22 at 2.53.31 PM.jpg" />

<img width="1736" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlQ4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3cb082d1882bbc438e2245608385b50d028dde2e/Screenshot%202024-07-22%20at%202.56.36%E2%80%AFPM.jpg" alt="Screenshot 2024-07-22 at 2.56.36 PM.jpg" />

<img width="1132" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmI4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--31454e98ced5cf8788fbef4a111546a110fbd13b/Screenshot%202024-07-22%20at%202.57.31%E2%80%AFPM.jpg" alt="Screenshot 2024-07-22 at 2.57.31 PM.jpg" />

**Comment by cris-oddball** [comment]
Sending up through the pipeline to Prod and closing the ticket
