### ISSUE TITLE
Comp and Pen: Enrollment Confirmation SMS notification

### ISSUE THREAD

**Issue by kbelikova-oddball** [department-of-veterans-affairs/notification-api#1979]
## User Story - Business Need
Currently when Veteran opts-in for Comp and Pen notifications, we don’t provide them with any proof of enrollment. When Veteran selects the checkbox for payment notification nothing is being sent to Veteran to inform them about them enrolling in this service, until it’s the 22nd of the month - time for a notification. 

But due to the payment processing cut-off dates, [opt-in status] + [enrollment date] combination is very important:
If Veteran enrolls before the the 10th - they will receive their Comp and Pen notification the same month;
If Veteran enrolls after the 10th - they will receive their Comp and Pen notification the following month.

Such a gap between enrollment date and first notification can lead to confusion (Is their payment not coming this month? Is it just a notification not coming until next month?) and cause Veteran reach out to a help line to clarify, what we are actually trying to minimize to implementing Comp and Pen.

We’ve added a safeguard measure by including the information about this process timeline in Q&A section of payment history. 
But we should take a step further and send Veteran the “intro” Comp and Pen SMS that would be proof of their Comp and Pen enrollment:
**“VA Benefits: You are enrolled! Your notification is scheduled for [month-name]. Reply STOP to unsubscribe, HELP for link to access VA payment history.”**

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**       Veteran
**I want**     To receive an SMS confirmation of enrollment in Comp And Pen notifications
**So that**   I have a proof that I've opted-in and I know when my first notification will come.

**As a**       VA Notify stakeholder
**I want**    To inform Veterans that they've enrolled in Comp & Pen
**So that**   Veteran is not surprised by Comp and Pen notification timing. 

### Additional Info and Resources

- SMS template management:
  - We’ll need to create and manage a new SMS template, different from recurring Comp and Pen notifications.
  - We should try not to exceed 160 characters for content.

## Acceptance Criteria

GIVEN Veteran never enrolled in Comp and Pen notification
WHEN Veteran selects the “Payment notification” checkbox associated with Comp and Pen notifications
AND Date is **before** 10th of the month
THEN Veteran receives an SMS confirmation of enrollment in Comp & Pen: “VA Benefits: You are enrolled! Your notification is scheduled for [**current-month-name**]. Reply STOP to unsubscribe, HELP for link to access VA payment history.”

GIVEN Veteran never enrolled in Comp and Pen notification
WHEN Veteran selects the “Payment notification” checkbox associated with Comp and Pen notifications
AND Date is **after** 10th of the month
THEN Veteran receives an SMS confirmation of enrollment in Comp & Pen: “VA Benefits: You are enrolled! Your notification is scheduled for [**next-month-name**]. Reply STOP to unsubscribe, HELP for link to access VA payment history.”

- [x] @kbelikova-oddball to finalize content with @mjones-oddball and create the template in portal
- [x] Update the table to show that the individual has been sent a notification (use the id)
- [x] Update the Slide deck with the key win and a demo slide

## QA Considerations
- [ ] Robust testing in Perf; use staging va.gov to log in as a user to validate by flipping the toggle.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1979?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @mchlwellman

**Comment by npmartin-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/1979?planning-poker) with Zenhub @coreycarvalho

**Comment by MackHalliday** [comment]
# Notes 
- va_profile_opt_in_out_lambda_handler
- Can this only be tested in PERF? 
- Should I create a separate celery task?
- Any logic for opt out?

**Comment by MackHalliday** [comment]
Yesterday 
- Confirmed details on ticket and basic implementation 
- Talked to QA 
- Started on testing and method to POST to notification SMS 

Today 
- Continue on testing and POST

**Comment by MackHalliday** [comment]
Yesterday 
- Got basic method working with a lot of TODOs 
- Complete test without edges 

Thursday 
- Address TODOs especially parameter store values and exception handling 
- Complete test for edge cases 
- Get working on PERF

**Comment by MackHalliday** [comment]
Talked to @EvanParish and @k-macmillan this morning regarding various env values and parameter store values. 

Mack Halliday
  10:38 AM
OK so
1. Attached SMS sender id to lambda (Talk to Corey)
2. Use VA Notify API key parameter to create env values in lambda (per env). Env values point to parameter store value.
3. Build VANotify URL in lambda per env
(edited)

10:39
And to confirm - When making a POST /v2/notifications/sms do I need to include a service sender phone number or just the SMS sender id? (edited) 

Kyle MacMillan
  10:40 AM
Yep! Small revision to 2:
You'd use postman to generate an API key per-environment and add each to the parameter store-applicable parameter.
You do not need the number in the request, just the sms sender id.

**Comment by MackHalliday** [comment]
Friday 
- Tested on PERF. Issues with using request library, decided to switch to HTTPSConnection since already installed.
- Updated new code to use HTTPSConnection - running into issues with mocking datetime.now(). Tried to use freeze_time module but it does not work with logic for parameterizing value to test the datetime logic and personalization. 

Today 
- Continue to work on mocking 
- Test on PREF
- Submit PR.

**Comment by MackHalliday** [comment]
Yesterday 
- Implemented and tested code to encode jwt 
- Corrected logic to send ONLY opt in Comp and Pen confirmations 
- Add Exception handling
- Add more testing and testing clean up 

Today 
- Confirm values for template_ids, service_ids, and sms_sender_ids for each environment 
- Confirm values for `communicationChannelId` 
- Complete testing for Exception handling 
- Final round of testing on PERF

**Comment by MackHalliday** [comment]
# TODO 

- [ ] Finish unit testing for Exception 
- [ ] Confirm different env values for each environment 
   - [ ] service_id 
   - [ ] sms_sender_id 
   - [ ] comp_and_pen_api_key
- [ ] Confirm template_id and personalization for for each environment  
- [ ] Confirm value for `communicationChannelId` for Comp and Pen

**Comment by MackHalliday** [comment]
# OFFTRACK 
Implementation of ticket required the following 
- Generating JWT token from API key and service ID 
- Sending a POST request from lambda to `v2/notifications/sms` with JWT
- A small PR to update infra to add environment variables
- A migration update for `va local_cache`
- Saving the notification_id from POST  `v2/notifications/sms`. 
- Confirming all env variables in environment 
- Exception handling for new POST request from lambda to `v2/notifications/sms`  and saving notification_id to DB 
- Unit testing for all 
- Testing in PERF with TUD - redeploying migrations as needed. 
- <img width="536" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTFrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39741dfc8d6a8dde6b6824928642fb9380d3613e/Screenshot%202024-10-22%20at%2010.53.49%E2%80%AFAM.png" alt="Screenshot 2024-10-22 at 10.53.49 AM.png" />

**Comment by MackHalliday** [comment]
- Requirement clarification, `notification_id`  to be a string on the `va_profile_local_cache `

<img width="878" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjVrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1816136217cee275b1fad64c058e153bd41aecb3/Screenshot%202024-10-22%20at%2011.51.33%E2%80%AFAM.png" alt="Screenshot 2024-10-22 at 11.51.33 AM.png" />

**Comment by MackHalliday** [comment]
yesterday 
- Add logic and testing for adding notification_id to va_profile_local_cache table 
- Update migration 
- Talked to Kyle about env variables

Today 
- Test in PERF, need to confirm update to DB working
- Exception handling unit tests

**Comment by MackHalliday** [comment]
Need to figure out if we should keep `intergration_test` flag in the code? 


Mack Halliday
  10:26 AM
Hey I'm spending a little more time on testing.
There's a flag that can be passed into the test context of the lambda called integration_test ( It appears in the test as event['queryStringParameters'] = {'integration_test': "the value doesn't matter"}) . Within the lambda code itself - there's several if/else statements that determine if certain PUT requests are made and what the body of the code looks like. SO the lambda returns a different value if the intergration_test flag is set.
EXAMPLE - Line 412 is the final return of the lambda_handler.  Without the intergration_test flag, the lambda hander does NOT return the PUT body request to VAPROFILE.
Screenshot 2024-10-24 at 10.25.17 AM.png
 
Screenshot 2024-10-24 at 10.25.17 AM.png








10:28
When I started mocking out the new environment and correctly mocking out the PUT call to VAPROFILE and the new POST request to VANOTIFY, I noticed the intergration_test flag is not necessary anymore and returns a different value from the lambda handler if not on.
This of course changed the original testing.
10:29
I guess - My question is - Now that the mocking is correct and intergration_test flag is not necessary - should I go ahead and remove the if/else logic in the lambda using the intergration_test flag?
Or is that beyond this user story?

**Comment by cris-oddball** [comment]
PR Approved and merged, deployed to Perf. Testing there today.

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC01 - Opt-in to C&P Notification: expect logging statements from the Lambda that show a POST v2/notifications/sms was sent to that VAProfile ID, an insertion was made into the Cache with the notification_id, the notification was received with a status of Delivered.

VAProfileID 1550116
- First opted out and received logging messages from lambda to that effect (existing behavior), no notification sent.
- Changed to my number in TUD, then opted in.
<img width="1795" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzUxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--665ff5aca00926bb9c2d993e0be7d9964d97b581/Screenshot%202024-10-25%20at%207.55.39%E2%80%AFAM.jpg" alt="Screenshot 2024-10-25 at 7.55.39 AM.jpg" />

- Notification was delivered to my phone
<img width="1320" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFYxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6908ac7e8b22c60abd8f7042784b48c984a40aa4/IMG_0075.jpg" alt="IMG_0075.jpg" />

- Database shows notification insertion
<img width="387" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGgxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0252a1393c2bac85f725f8a4c5917de1fd757b2a/Screenshot_2024-10-25_at_7_58_00%E2%80%AFAM.jpg" alt="Screenshot_2024-10-25_at_7_58_00 AM.jpg" />

- GET v2/notifications/:notification_id reports `"status": "delivered",`

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC02 - Same user as above, opted out, opted back in. A new notification was sent and the notification_id in the database was overwritten with the new notification.

> [INFO]	2024-10-25T14:00:22.165Z	ea4fa9f2-b114-4400-bfee-843751a50001	Successfully updated VAProfileLocalCache with notification_id dd97d58b-1a4d-47bb-9302-0e402a3dfc33 for va_profile_id 1550116.
<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUIxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80c97d9d3772742398b62a3e9b192ac34c7ce462/Screenshot_2024-10-25_at_8_01_03%E2%80%AFAM.jpg" alt="Screenshot_2024-10-25_at_8_01_03 AM.jpg" />

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC04 - Reply STOP to the C&P sms sender, then opt-in

- Did not receive message (expected)
- Notification ID inserted into DB

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC04 - Reply STOP to the C&P sms sender, then opt-in

- Did not receive message (expected)
- Notification ID inserted into DB

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC04 - Reply STOP to the C&P sms sender, then opt-in

- Did not receive message (expected)
- Notification ID inserted into DB

**Comment by cris-oddball** [comment]
**QA VALIDATION IN PERF - PASSED**

- [ ] TC04 - Reply STOP to the C&P sms sender, then opt-in

- Did not receive message (expected)
- Notification ID inserted into DB

**Comment by cris-oddball** [comment]
Deploying to Staging to only validate the Happy Path (TC01).

**Comment by cris-oddball** [comment]
QA

**Comment by MackHalliday** [comment]
[See comment in Slack. ](https://oddball.slack.com/archives/C036AE08HA7/p1729892061618549?thread_ts=1729877481.605849&cid=C036AE08HA7)

**Comment by cris-oddball** [comment]
Moving back to QA for Staging tests.
It appears that the COMP_AND_PEN_OPT_IN_TEMPLATE_ID was not populated for either Staging or Prod. It is unclear why do the lack of info on the order of operations, however, the SSM param store was populated with these values. I re-deployed Infra main to staging and prod this morning, which then populated the values in both lambdas.

Testing on Staging can resume.

**Comment by cris-oddball** [comment]
Pre-deployment validation in PROD by sending an sms through Postman as per the env vars on the Lambda. The text was received from the correct short code and the status was delivered. This can now go to Prod.

**Comment by cris-oddball** [comment]
Deployed to Prod. Kyle opted in using his own VA account. Notification was received to his phone. 

Closing ticket as Done.
