### ISSUE TITLE
API-2079 Add histogram metric type for tracking SMS content length

### ISSUE THREAD

**Issue by k-macmillan** [department-of-veterans-affairs/notification-api#2079]
## User Story - Business Need
We need to be aware of excessive content length in SMS. This ticket is to start sending the metric to statsd so we can make informed decisions.

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** Veteran      
**I want** SMS sent to me to be a reasonable length   
**So that** there is less confusion regarding the notification  

### Additional Info and Resources

- The `send_sms_to_provider` method creates the data for the "content" field used in `send_sms`
- The data is changed to a string in the method call, that should probably be pulled to a little before the method call so we can set the gauge
- [Setting a statsd gauge](https://python-statsd.readthedocs.io/en/latest/statsd.gauge.html#statsd.gauge.Gauge.set) in python

The gauge should be placed in the same area as this log:
![Image](https://github.com/user-attachments/assets/cf2b95db-4455-4607-b857-05108a003063)

This is currently visible in DD:
![Image](https://github.com/user-attachments/assets/f2c4f885-75da-4890-b767-78ed853bf2ad)

This is 1600 characters with at most 45 characters per line (about what Android has as default):
```
Lorem ipsum odor amet, consectetuer 
adipiscing elit. Posuere facilisi natoque 
tincidunt pellentesque rutrum aenean. Taciti 
nisl pulvinar ex magnis faucibus nascetur. 
Ultricies hendrerit bibendum urna ultricies 
iaculis massa varius egestas. Aliquam aliquam
 egestas neque; dolor parturient maecenas 
dictum. Malesuada litora aptent dignissim 
egestas metus inceptos taciti. Imperdiet 
congue eget donec condimentum parturient 
fermentum. Lorem class varius nostra 
facilisis convallis cubilia? Sem pulvinar 
parturient turpis fringilla ipsum tellus.

Montes consequat inceptos hendrerit libero 
consequat magna. Nec in pharetra potenti 
egestas dignissim. Luctus ullamcorper mi 
rhoncus erat quisque malesuada. Ex magna odio
 consequat mauris molestie metus mi 
ullamcorper. Dictum curabitur amet maecenas 
conubia dui parturient. Nascetur tellus enim 
duis vehicula et ex sapien ipsum senectus. 
Non felis adipiscing sociosqu lobortis 
integer commodo luctus.

Fermentum adipiscing quis elit ut purus urna.
 Maecenas mattis euismod sem cras sagittis 
pretium fermentum a. Eros montes netus 
cubilia enim ligula. Vitae class mattis 
imperdiet vel sem quis accumsan augue. 
Dignissim quis senectus fusce sed cursus 
fringilla interdum elementum nec. Ante 
torquent curabitur placerat porta feugiat 
donec fringilla. Nascetur nullam finibus 
feugiat conubia lectus et efficitur auctor 
hac.

Nunc turpis mattis netus id consectetur massa
 primis vulputate. Dictum nisi platea 
penatibus semper in. Pulvinar rutrum nunc; 
lacus cras ut metus. Montes in ex phasellus 
penatibus purus torquent sagitt.
```

## Acceptance Criteria

- [x] A statsd gauge is used to record/set the content length e.g. `len(content)`
- [x] Metric appears in Datadog
- [x] Current log remains
- [ ] ~~Pipeline Grok removed from DD (seek devops/lead)~~

- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by kbelikova-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/2079?planning-poker) with Zenhub @cris-oddball @EvanParish @k-macmillan @kalbfled @MackHalliday @mchlwellman

**Comment by mchlwellman** [comment]
I have added the gauge, and it's in Datadog, however the [documentation](https://docs.datadoghq.com/metrics/types/?tab=gauge#metric-types) for a gauge says that it only submits the last value received during a flush interval, the others are dropped, which isn't ideal. I think Datadog uses a [flush interval of 10 seconds](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#how-it-works).  To address this shortcoming, Datadog has added a `histogram` metric type to it's [statsd implementation](https://github.com/DataDog/datadogpy/blob/362e187977478176e4e6049cd69c8e0267f231e6/datadog/dogstatsd/base.py#L950).  We use our own [statsd client](https://github.com/department-of-veterans-affairs/notification-utils/blob/979cbb61dcd6f67a04f64d1b01c40acafb162b1a/notifications_utils/clients/statsd/statsd_client.py#L21) derived from the [basic python implementation](https://github.com/jsocol/pystatsd/blob/c687a4e6bcad1314088cf4934580a8bf46290a8a/statsd/client/base.py#L8).  A statsd datagram looks like this `namespace.metric:value|type`.  The `type` field is a single character, and for the new histogram type, Datadog is using `h`, so I added a corresponding `histogram` method to our internal statsd client. I've tested it against Datadog and against a local Graphite instance (which doesn't support histograms). The metric shows in both, although I don't know why it does in Graphite.

**Comment by cris-oddball** [comment]
PRs for utils and api merged. Holding deploy until after resolving C&P send issue. Will be up by EOD.
