### ISSUE TITLE
Setup 'Receipt of Application' Email for 526EZ in VANotify

### ISSUE THREAD

**Issue by QaysarA** [department-of-veterans-affairs/notification-api#71]
**Acceptance Criteria:**
GIVEN a disability compensation form 526 is submitted successfully in dev
WHEN a confirmation email is received
AND the confirmation webpage displays personalization data
THEN the user's first name, last name, claim id, and date submitted that match the webpage are shown in the email.

**Assumptions:** 
- Content is complete
- Design is complete
- This will need to be done for Dev an Staging 
- There will be separate work need to be done for Production 

**Tasks:**
- update vets-api to include personalization in template based on [#82] (*form526_submission.rb*)
  - [x] veteran full name
  - [x] claim ID
  - [x] date submitted
(these should match what's displayed on the form submission confirmation screen)
- [x] update the template (id: `f2b762d1-6bd0-46df-9559-234ceb73effb`) on the *development* notification api to include personalization as required parameters
- [ ] ~update the template on the *staging* notification api to include personalization as required parameters~ -> This task requires that a staging template already exists, which is defined in #76. When setting up the template, the personalization can be copied over from the dev template.

Additional tasks based on desk check:
- [x] Make sure date_submitted displayed in the email shows the hour, minute, and timezone (as UTC). For example: `July 22, 2020 14:15 UTC`
     - we noticed that when the form is submitted at 9pm EST, the webpage says the current day, but the email shows the next day, due to a timezone issue. 
- [x] Change the email to use the full name. According to `src/applications/disability-benefits/all-claims/content/confirmation-page.jsx` from `vets-website`, the full name displayed includes first, middle, last, and suffix. We are currently only displayed first and last in our email, but it should be consistent with the webpage.
- [x] Create additional tests to check different user names (only first and last, first middle last,  first middle last suffix)
- [x] Full name should be all uppercase

**Outstanding questions:**
- [x] Just first name and last name, or middle name and title too? May depend on what's in the database, but also @toddstanich to figure out what's desired
  - Use the full name in order to match the screen text

**Out Of Scope:** 
- We must gracefully handle errors if the template is not available/correct. This scenario will be covered in #86
- Completed discussion if changes required for the email on multiple OS, browsers, and email clients are part of this story. The testing design and accessibility with clients and browsers will be part of a separate story. Working on access to a tool that is used at the VA or work with procurement. This scenario will be covered in #102
- Completed discussion if changes required for Accessibility are part of this story. They will be part of a separate story #102
- Include alt text for all the images, current design has VA logo. This scenario will be covered in #92
- The appropriate From email address needs to be included 'notify@messages.va.gov' Default. Can add for each use case. Would require the govdelivery account setup, if not then this would be done in a separate card #103
- The appropriate Reply email needs to be included and if not add messaging and content to indicate that. (Default - do-not-reply email address) research defined policies currently by the Caseflow team with Appeals use case. This will be covered in #103

**Comment by saman-moshafi-va** [comment]
We modified the code on Wednesday, July 8, 2020.  Unfortunately we have not been able to test it in the review environment.  Will change the PR so the changes can be submitted on Staging and tested on staging.

**Comment by sarahproof** [comment]
Did we get an answer to the outstanding question?

**Comment by saman-moshafi-va** [comment]
> Did we get an answer to the outstanding question?

The email content should be as close as possible to the message on the screen, hence we will try to use the full name if the data is available otherwise build it.

**Comment by marisahoenig** [comment]
[Useful thread](https://dsva.slack.com/archives/C010R6AUPHT/p1595358415143000) re: `updated_at` and `created_at`.

In summary, when we do the `submit_all_claim` POST request, we parse the request body (526 form data) and try to save it to the database `form526_submissions` table. This entry is timestamped, e.g it gets a `created_at` value. This Sidekiq job is async and retried many times, trying to submit the forms to EVSS. Once successful, the `form526_submissions` entry is updated, `updated_at` has the new date, and `workflow_complete` is set to true.

`created_at` - the time the user hit submit
`updated_at` - the time EVSS accepted the form

On the webpage, `submittedAt` is displayed, which is the value of `created_at`. In our email, we are trying to send the `updated_at` date, which has the value of `created_at` before the job is complete.

**Comment by marisahoenig** [comment]
Based on further discussions, we decided that:
- The full name in the email should be in uppercase (including suffix)
- Leave in the suffix even though right now we're not seeing it display on the webpage for one of our test users.
- The date should be the date that the claim was received— the `created_at`value.

**Comment by marisahoenig** [comment]
Based on further discussions regarding timezone, "we can leave the time component out." We need to discuss with stakeholders what we should display.

This is due to the problem that if you submit the application at 9pm EST (or similar time), the date in the email will show the date in UTC. So, it would show you tomorrow's date instead of today's.

**Comment by marisahoenig** [comment]
Awaiting approval on PR:
https://github.com/department-of-veterans-affairs/vets-api/pull/4556

**Comment by sarahproof** [comment]
When there isn't a middle name, the email sends out with NULL
![middle_null](https://user-images.githubusercontent.com/56557361/90059257-7c861580-dca8-11ea-9455-335647940c82.png)

**Comment by saman-moshafi-va** [comment]
> When there isn't a middle name, the email sends out with NULL
> ![middle_null](https://user-images.githubusercontent.com/56557361/90059257-7c861580-dca8-11ea-9455-335647940c82.png)

We logged to va staging as the user vets.gov.user+38@gmail.com and the profile screen displays
<img width="503" alt="Screen Shot 2020-08-17 at 2 00 35 PM" src="https://user-images.githubusercontent.com/56931061/90428519-1cb9b100-e092-11ea-9dcc-24db6f3c7291.png">

**Comment by marisahoenig** [comment]
This particular user has "Null" as a string for its middle name. Moving to review
