### ISSUE TITLE
TODO comment Get sender name and sender email separately

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#880]
## User Story - Business Need

This TODO comment asks that we take the sender name and email separately rather than together.

It is also in `notification-api/app/clients/email/govdelivery_client.py` and is recommended that we should move this code up to **before a provider is called** so that any provider that is used gets the same information (since all providers will likely have this code to strip out email from name).

Suggestion: upon receiving the payload, run a "Sanitize" method that does any necessary formatting of the payload before sending it to a provider.

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/clients/email/govdelivery_client.py#L66): Sometimes the source is `Foo <foo@bar.com>` vs just `foo@bar.com`. Current code gets the `source` like :
```
if "<" in source:
    source = source.split("<")[1].split(">")[0]
```
Take sender name and email separately.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**   VANotify
**I want**   to reduce tech debt and handle TODO comments
**So that**  development is more straightforward

## Engineering Checklist

- [ ] move this code up to **before a provider is called** so that any provider that is used gets the same information
- [ ] from source, take sender name and email separately.
- [ ] remove the todo comment from the code

## Acceptance Criteria

- [ ] sending through providers should function the same as it does before this change (no regressions introduced)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/880?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by jakehova** [comment]
We should move this code up to before a provider is called so that any provider that is used gets the same information (since all providers will likely have this code to strip out email from name).  

Suggestion: upon receiving the payload, run a "Sanitize" method that does any necessary formatting of the payload before sending it to a provider.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/880?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
@cris-oddball Unless we were facing issues with govdelivery being a supported provider I wouldn't want to remove the ability.  God forbid something happened to Amazon we could easily revert to sending email thru govdelivery which used to be the email provider before Amazon. (before our time)

**Comment by cris-oddball** [comment]
TODO still exists in Main. Probably still needed.

**Comment by k-macmillan** [comment]
Closing.
