### ISSUE TITLE
TODO Refactor validation after merging inbound number & sms_sender

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#881]
## User Story - Business Need
TODOs are comments in the codebase that should be handled. This TODO asks to "Refactor validation after merging inbound number & sms_sender"

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/dao/service_sms_sender_dao.py#L88): Refactor validation after merging inbound number & sms_sender
```
# TODO - Refactor validation after merging inbound number & sms_sender
    if (rate_limit is not None and rate_limit_interval is None) or \
            (rate_limit_interval is not None and rate_limit is None):
        raise SmsSenderRateLimitIntegrityException("Provide both rate_limit and rate_limit_interval.")

```

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**   to ensure a clean codebase by resolving TODO items
**So that**  development is straightforward

## Engineering Checklist

- [ ] Determine what validation needs to be refactored
- [ ] Refactor that validation
- [ ] Remove the TODO

## Acceptance Criteria

- [ ] The feature has no regressions introduced by this work.

- validation beyond a regression test depends on outcome of convo with dev

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/881?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/881?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
TODO still exists in Main. Neither Evan or Dave know what any of it means. Suggest changing the ticket to remove the TODO.

**Comment by k-macmillan** [comment]
Closing. Incoming sms is getting a complete refactor at another time.
