### ISSUE TITLE
TODO Remove or extract attachment handling to separate method

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#883]
## User Story - Business Need
TODOs in the codebase indicate areas of tech debt and should be resolved or removed. 

We should be breaking up functions to make sure they each only handle one concern. The code below should be broken out into its own function and removed from the [`send_email_to_provider`](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/delivery/send_to_providers.py#L106) function. 

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** to break up functions to make sure they each only handle one concern
**So that** the code is more easily maintained

### Additional Info and Resources

This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/delivery/send_to_providers.py#L119)  relates to attachments in `personalisation`

```
    # TODO: #883 remove that code or extract attachment handling to separate method
    # Extract any file objects from the personalization
    file_keys = [
        k for k, v in (notification.personalisation or {}).items() if isinstance(v, dict) and 'file_name' in v
    ]
    attachments = []

    personalisation_data = notification.personalisation.copy()

    for key in file_keys:
        uploaded_attachment_metadata: UploadedAttachmentMetadata = personalisation_data[key]
        if uploaded_attachment_metadata['sending_method'] == 'attach':
            file_data = attachment_store.get(
                service_id=service.id,
                attachment_id=uploaded_attachment_metadata['id'],
                decryption_key=uploaded_attachment_metadata['encryption_key'],
                sending_method=uploaded_attachment_metadata['sending_method']
            )
            attachments.append({
                "name": uploaded_attachment_metadata['file_name'],
                "data": file_data
            })
            del personalisation_data[key]
        else:
            personalisation_data[key] = personalisation_data[key]['url']
```

## Engineering Checklist

- [ ] Break up the code under consideration to a distinct method outside of the current function
- [ ] Remove the TODO comment

## Acceptance Criteria

- [ ] Functionality should be maintained after this code change
- [ ] Unit tests are added for the new function

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._

- [ ] no regressions are introduced by this code change

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/883?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/883?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/883?planning-poker) with Zenhub @ldraney

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/883?planning-poker) with Zenhub @nikolai-efimov

**Comment by cris-oddball** [comment]
TODO still exists in Main, we can do attachments inside personalisation? Might be useful for ENP?

**Comment by k-macmillan** [comment]
Will revisit attachments when the VA requests them.
