### ISSUE TITLE
SPIKE: TODO Use "/v2/" route in Template class once available

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#884]
## User Story - Business Goal
The code is littered with TODO comments that are not linked to tickets and not well understood. This TODO concerns using the `/v2/templates` route in the Template class of `notification-api/app/models.py` "when available". The `/v2/templates` route has been available for some time.

The goal of this ticket is to determine if we should deprecate the existing templates route, `{{notification-api-url}}/service/{{service-id}}/template` for the new template route` {{notification-api-url}}/v2/templates`

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**    VANotify
**I want**   to clean up TODO comments
**So that**    the code is more readily maintained

**As a**    VANotify
**I want**   to determine the utility of the v2 template route
**So that**  we can provide a better service to our clients

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/models.py#L979): Use "/v2/" route in `Template` class once available.
```
  def get_link(self):
      # TODO: use "/v2/" route once available
      return url_for(
          "template.get_template_by_id_and_service_id",
          service_id=self.service_id,
          template_id=self.id,
          _external=True
      )
```

## Acceptance Criteria & Checklist

- [ ] Technical Documentation has been created and linked in the glossary
- [ ] Learnings have been shared with the team, and decisions have been documented
- [ ] Tickets for next steps have been identified and created
  - [ ] Any new tickets created should handle the TODO comment, either by adding in a ticket number to that comment or by removing the TODO comment (depends on the work)

Completed research addresses the problems and/or answers the questions below:  

1. It is unclear why a v2 route even exists for templates: what was it trying to solve? 
2. Should we sunset the existing template route (noting that Strike directly accesses the DB for template crud, without using our endpoints) and perform the work asked in the TODO?
3. Should we sunset the v2 route and just remove the TODO in the code?

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/884?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/884?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
@cris-oddball I left this guy in backlog because it had more content in it than usual. Not sure if that will make it easier to get to a review ready state.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/884?planning-poker) with Zenhub @cris-oddball @EvanParish @kalbfled @ldraney @nikolai-efimov

**Comment by k-macmillan** [comment]
Closing.
