### ISSUE TITLE
TODO: Remove the code once VA_SSO_ENABLED toggles is removed

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#885]
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/oauth/rest.py#L102): Remove the code once VA_SSO_ENABLED toggles is removed
```
  try:
      user = create_or_retrieve_user(
          email_address=verified_email,
          identity_provider_user_id=verified_user_id,
          name=verified_name)
      return _successful_sso_login_response(user)
  except IncorrectGithubIdException as e:
      current_app.logger.error(e)
      statsd_client.incr('oauth.authorization.github_id_mismatch')
      return make_response(redirect(f"{current_app.config['UI_HOST_NAME']}/login/failure"))
```

Additionally:
- [ ] Remove all feature flag checks associated with VA_SSO_ENABLED
- [ ] Remove from task definitions
- [ ] Remove from tests.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/885?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/885?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
We don't need a separate ticket for this, so closing. 
Info added to [#1936](https://github.com/department-of-veterans-affairs/notification-api/issues/1936) which removes the feature flag and associated code in question.
