### ISSUE TITLE
TODO: delete unnecessary todo comments

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#886]
## User Story - Business Need
The codebase is littered with TODOs. 

This effort is to clean up two unneeded TODOs
- to add defaults or request validation to the method `get_usage_for_all_services()` in [app/platform_stats/rest.py](https://github.com/department-of-veterans-affairs/notification-api/blob/6efbd56716f2ccbcc09ce926bdc4f9a135432ed1/app/platform_stats/rest.py#L81C34-L81C34)
- to add email costs to that method

We have determined that this is unnecessary (see comment in ticket) so this ticket is just to remove the TODO from this file.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**  to not have unneeded TODOs in the codebase
**So that**  development is straightforward

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/platform_stats/rest.py#L82): Add defaults or request validation
```
    # TODO: Add defeaults or `request` validation
    start_date = request.args.get('start_date')
    end_date = request.args.get('end_date')
```

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/platform_stats/rest.py#L97): Add email costs in [get_usage_for_all_services](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/platform_stats/rest.py#L81)
```
    # TODO: Add email costs?
    for s in sms_costs:
        entry = {
            "organisation_id": str(s.organisation_id) if s.organisation_id else "",
            "organisation_name": s.organisation_name or "",
            "service_id": str(s.service_id),
            "service_name": s.service_name,
            "sms_cost": float(s.sms_cost),
            "sms_fragments": s.chargeable_billable_sms,
            "letter_cost": 0,
            "letter_breakdown": ""
        }
```

## Engineering Checklist

- [ ] Remove both TODOs

## Acceptance Criteria

- [ ] the TODOs are gone.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/886?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by kalbfled** [comment]
As written, the code tests that the given dates are in the same fiscal year and that the start_date is earlier than the end_date.  If not, or if either date is None, InvalidRequest is raised.  This seems like an appropriate implementation.  The recommendation from me and @ldraney is to delete the TODO comment.

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/886?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
from the duplicated ticket
[Uploading... Screen Shot 2023-09-12 at 3.09.35 PM.jpg]

**Comment by cris-oddball** [comment]
code approved and merged
