### ISSUE TITLE
TODO: json_to_validate could raise AttributeError

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#888]
## User Story - Business Need
The codebase is littered with TODO comments. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/schema_validation/__init__.py#L93) asks to add exception handling to schema validation in `/app/schema_validation/__init__.py`

In that `__init__.py` file, a method assumes that a variable is a dictionary, but this could be a string, None or some other type that does not have a `.get() `method. This could raise an attribute error which would throw a traceback and not execute properly. Properly handle this Attribute Error

- [x] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**  to handle properly possible exceptions 
**So that** the application is stable and reliable.

### Additional Info and Resources

- [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/schema_validation/__init__.py#L93)
 `json_to_validate` could be a `string`, `None`, or some other type that does not have the `get` method, raising an attribute error.
```python
def validate(json_to_validate, schema):
    validator = Draft7Validator(schema, format_checker=format_checker)
    errors = list(validator.iter_errors(json_to_validate))
    if len(errors) > 0:
        ...
    # TODO - This assumes that json_to_validate is a dictionary.  It could raise AttributeError.
    if json_to_validate.get('personalisation'):
        json_to_validate['personalisation'], errors = decode_personalisation_files(
            json_to_validate.get('personalisation', {})
        )
        if len(errors) > 0:
            error_message = json.dumps({'status_code': 400, 'errors': errors})
            raise ValidationError(error_message)
    return json_to_validate
```

## Engineering Checklist

- [ ] Add exception handling for AttributeError
- [x] Remove TODO comment
- [x] add/edit unit tests as needed

## Acceptance Criteria

- [x] Any AttributeError for this method is caught.
- [x] `json_to_validate` type is checked as a dictionary prior to any processing ([guard statement](https://en.wikipedia.org/wiki/Guard_(computer_science)))
- [x] Existing dictionary check is removed
- [x] This work is added to the sprint review slide deck (key win bullet point and demo slide)

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/888?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/888?planning-poker) with Zenhub @justaskdavidb2

**Comment by npmartin-oddball** [comment]
Need to update to say that it handles check in method.

**Comment by mchlwellman** [comment]
I've addressed the TODO, but some of the AC in this ticket were irrelevant, maybe due to the age.

**Comment by mchlwellman** [comment]
I've opened a PR, but late in the day, so this will be rolling over until it's approved and merged.
