### ISSUE TITLE
SPIKE (todo comment): Rename method (and endpoint)

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#890]
## User Story - Business Goal

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)
The code base is littered with TODOs. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/template_statistics/rest.py#L45) concerns renaming a method and an endpoint in /app/template_statistics/rest.py

Determine if this is necessary or not.

If so, create a new ticket detailing the work necessary and put that ticket number in that comment.
If not, remove that TODO comment.

**As a**  VANotify
**I want**  to clean up TODO comments 
**So that** the codebase is tidy and development straightforward.

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/template_statistics/rest.py#L45): Rename method (and endpoint?)

```python
@template_statistics.route('/<template_id>')
def get_template_statistics_for_template_id(service_id, template_id):
    template = dao_get_template_by_id_and_service_id(template_id, service_id)

    data = None
    notification = dao_get_last_template_usage(template_id, template.template_type, template.service_id)
    if notification:
        data = notification_with_template_schema.dump(notification).data

    return jsonify(data=data)
```

## Acceptance Criteria & Checklist

- [ ] A determination is made as to whether the work requested is valid or not 
- [ ] If not, open a pr against this ticket to remove the TODO
- [ ] Otherwise:
  - [ ] Learnings have been shared with the team, and decisions have been documented
  - [ ] Tickets for next steps have been identified and created

Completed research addresses the problems and/or answers the questions below:  

1. Why would this method and endpoint need to be renamed?
2. Does Strike use this endpoint to display template statistics?

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/890?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/890?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
This this TODO still exists in Main and might be worthwhile as a spike to understand it for ENP.

**Comment by npmartin-oddball** [comment]
Closing.
