### ISSUE TITLE
TODO: Update predetermined list of simulated email addresses

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#891]
## User Story - Business Need
The code base is littered with TODO comments. This TODO asks to pass `simulated ` as a parameter to
`process_sms_or_email_notification` or to mock the undesired side-effects in test code, rather than using a predetermined list of e-mail addresses defined or simulation

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**   to remove tech debt
**So that**  to have a maintainable codebase

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/v2/notifications/post_notifications.py#L172): This value is computed using a predetermined list of e-mail addresses defined to be for simulation.  A better approach might be to pass "simulated" as a parameter to [process_sms_or_email_notification](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/v2/notifications/post_notifications.py#L202) or to mock the undesired side-effects in test code.
```python
def process_sms_or_email_notification(*, form, notification_type, api_key, template, service, reply_to_text=None):
    form_send_to = form["email_address" if (notification_type == EMAIL_TYPE) else "phone_number"]

    send_to = validate_and_format_recipient(
        send_to=form_send_to,
        key_type=api_key.key_type,
        service=service,
        notification_type=notification_type
    )

    # Do not persist or send notification to the queue if it is a simulated recipient.
    #
    # TODO (tech debt) - This value is computed using a predetermined list of e-mail addresses defined
    # to be for simulation.  A better approach might be to pass "simulated" as a parameter to
    # process_sms_or_email_notification or to mock the undesired side-effects in test code.
    simulated: bool = simulated_recipient(send_to, notification_type)
```

See @EvanParish for more details.

## Engineering Checklist

- [ ] Determine whether to pass "simulated" as a parameter to process_sms_or_email_notification or to mock the undesired side-effects in test code.
- [ ] Implement the above determination
- [ ] Remove the TODO comment
- [ ] Unit tests as needed

## Acceptance Criteria

- [ ] The code functions as before
- [ ] There is no TODO comment here
- [ ] Unit tests pass
- [ ] The QA Suite passes

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/891?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/891?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
TODO still exists in Main. Unclear if worth the effort.

**Comment by npmartin-oddball** [comment]
Closing.
