### ISSUE TITLE
TODO Refactor identifier.py to use classes instead of dictionaries

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#892]
## User Story - Business Need
The code base is littered with TODOs. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/va/identifier.py#L4) asks to reformat the entire file `app/va/identifier.py` to be more pythonic and use Classes that contain `suffix`, `oid` properties etc. instead of dictionaries outside of the class

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**  to be more pythonic
**So that**  the code is easier to maintain

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/va/identifier.py#L4): Refactor /app/va/identifier.py to have actual classes that contain `suffix`, `oid` properties etc instead of all dicts.

The file fiest defines a class with one method:
```python
class IdentifierType(Enum):
    VA_PROFILE_ID = 'VAPROFILEID'
    PID = 'PID'
    ICN = 'ICN'
    BIRLSID = 'BIRLSID'
    EDIPI = 'EDIPI'

    @staticmethod
    def values():
        return list(x.value for x in IdentifierType)


def is_fhir_format(identifier_value: str) -> bool:
    return identifier_value.count('^') >= 1
```

Then, two constants are defined in the file that are dictionaries. I believe this is where the previous team thought this could be better handled inside of a class (I suppose as self variables? It is unclear). Are these constants used elsewhere?

``` python
FHIR_FORMAT_SUFFIXES = {
    IdentifierType.ICN: "^NI^200M^USVHA",
    IdentifierType.PID: "^PI^200CORP^USVBA",
    IdentifierType.VA_PROFILE_ID: "^PI^200VETS^USDVA",
    IdentifierType.BIRLSID: "^PI^200BRLS^USVBA",
    IdentifierType.EDIPI: '^NI^200DOD^USDOD'
}

OIDS = {
    IdentifierType.ICN: '2.16.840.1.113883.4.349',
    IdentifierType.PID: '2.16.840.1.113883.4.349',
    IdentifierType.VA_PROFILE_ID: '2.16.840.1.113883.4.349',
    IdentifierType.BIRLSID: '2.16.840.1.113883.4.349',
    IdentifierType.EDIPI: '2.16.840.1.113883.3.42.10001.100001.12',
}
```

Another class is then defined to handle exceptions
```python
class UnsupportedIdentifierException(Exception):
    failure_reason = 'Unsupported identifier'
```

Then two methods are defined, one to transform the recipient_identifer to FHIR output and one to do the reverse transformation.
```python
def transform_to_fhir_format(recipient_identifier):
    try:
        identifier_type = IdentifierType(recipient_identifier.id_type)
        return f"{recipient_identifier.id_value}{FHIR_FORMAT_SUFFIXES[identifier_type]}"
    except ValueError as e:
        raise UnsupportedIdentifierException(f"No identifier of type: {recipient_identifier.id_type}") from e
    except KeyError as e:
        raise UnsupportedIdentifierException(f"No mapping for identifier: {identifier_type}") from e


def transform_from_fhir_format(fhir_format_identifier: str) -> str:
    return fhir_format_identifier.split('^')[0]
```

 One wonders if this couldn't all be handled in a single class with methods and the dictionaries as self.fhir_format_suffixes and self.oids

Note that this is imported by another file:
```
# app/va/mpi/mpi.py

from app.va.identifier import (
    IdentifierType,
    transform_to_fhir_format,
    is_fhir_format,
    FHIR_FORMAT_SUFFIXES,
    transform_from_fhir_format,
```

and another import of one of the constants here:
```python
# app/va/va_profile/va_profile_client.py
from app.va.identifier import is_fhir_format, transform_from_fhir_format, transform_to_fhir_format, OIDS, IdentifierType
```

## Engineering Checklist

- [ ] Determine if this refactor is worth doing
- [ ] If so:
  - [ ] Implement a proper classes in this file
  - [ ] Remove the TODO comment
- [ ] If not:
  - [ ] Remove the TODO comment

## Acceptance Criteria

- [ ] The app functions as before (no regressions)
- [ ] The TODO comment is gone

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/892?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/892?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/892?planning-poker) with Zenhub @nikolai-efimov

**Comment by cris-oddball** [comment]
TODO still exists in Main, nice to have but not a need to have. ENP will replace much of this anyway.

**Comment by npmartin-oddball** [comment]
Closing.
