### ISSUE TITLE
TODO: Use default communication item settings

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#893]
## User Story - Business Need
The codebase is littered with TODO comments. This TODO asks to use the default communication item settings instead of just raising CommunicationItemNotFoundException

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** to resolve issues noted in TODOs
**So that**  so that the code base is straightforward to develop against

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/main/app/va/va_profile/va_profile_client.py#L298): use default communication item settings when that has been implemented
```python
   self.statsd_client.incr("clients.va-profile.get-communication-item-permission.no-permissions")
```

The class `VAProfileClient` in `app/va/vaprofile/va_profile_client.py` uses a method `get_is_communication_allowed()`. The TODO is within this method . Partial screenshot:
![Screen Shot 2023-09-13 at 2 03 37 PM](https://github.com/department-of-veterans-affairs/notification-api/assets/111803622/9f808606-fabd-4e7d-90d4-d0538b03105e)

We believe the TODO is asking that defaults should be used instead of raising CommunicationItemNotFoundException. [Here](https://github.com/department-of-veterans-affairs/notification-api/blob/72465e2d5313c95312707493146644579c184d8f/app/celery/lookup_recipient_communication_permissions_task.py#L97) is where that exception is caught upstream (:zap: Note that the file linked in this paragraph no longer exists in Main).  It looks like permission is allowed if the boolean "default_send_indicator" field of the communication item is True. 

We can either delete to TODO comment as unneeded or we can cutting and pasting the logic that currently is upstream where the TODO is.

## Engineering Checklist

- [ ] Determine if the TODO comment is relevant
- [ ] If it is, then where the TODO comment is, cut/paste the logic from `/app/celery/lookup_recipient_communication_permissions_task.py#L97` 
- [ ] If it is superfluous, then just delete the TODO comment

## Acceptance Criteria

- [ ] The TODO is gone
- [ ] The feature works as it is currently does, with no regressions introduced.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/893?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/893?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
@mjones-oddball did we implement default communication item settings?

**Comment by mjones-oddball** [comment]
@cris-oddball I'm not sure I know what that means. Do you have any more context? Previously, we were always using default send logic if a communication item id was present on a template. Now, since adding explicit consent, we check the communication item table first to determine what type of logic to use for the applicable communication item id when doing a lookup for preference.

**Comment by cris-oddball** [comment]
@mjones-oddball thanks, I'm not sure of the original intent of the TODO; it was written two years ago by a dev from the previous team. I'll see if one of the engineers understands the intent.

**Comment by cris-oddball** [comment]
From Dave:

> I think it's saying that defaults should be used instead of raising CommunicationItemNotFoundException.

> [here](https://github.com/department-of-veterans-affairs/notification-api/blob/72465e2d5313c95312707493146644579c184d8f/app/celery/lookup_recipient_communication_permissions_task.py#L97) is where that exception is caught upstream.  It looks like permission is allowed if the boolean "default_send_indicator" field of the communication item is True.

> I probably would just delete that comment or replace it by cutting and pasting the logic that currently is upstream.

**Comment by cris-oddball** [comment]
No idea what is being asked for here and this stuff was all recently refactored by IIR. Suggest just changing this ticket to 'remove the TODO comment'.

**Comment by npmartin-oddball** [comment]
Closing.
