### ISSUE TITLE
TODO Add retries to vetext client for certain status codes

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#894]
## User Story - Business Need
TODO comment indicate areas of technical debt and should be resolved or removed. 

This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/app/va/vetext/client.py#L56) comment asks if retries are needed in the  class VETextClient for the method `send_push_notification` if the following status codes are returned from `mobile/push/send`: [429, 500, 502, 503, 504]

Given that `VETextRetryableException` is raised, we probably should be retrying.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**   to ensure that if we can retry we should, and if we should not then we do not
**So that**   the app is stable and reliable

**As a**  VANotify
**I want**   to ensure that TODO comments do not litter the codebase
**So that**  development is straightforward

### Additional Info and Resources

```
        except requests.HTTPError as e:
            self.logger.exception(e)
            self.statsd.incr(f"{self.STATSD_KEY}.error.{e.response.status_code}")
            if e.response.status_code in [429, 500, 502, 503, 504]:
                raise VETextRetryableException from e
                # TODO: add retries?
            elif e.response.status_code == 400:
                self._decode_bad_request_response(e)
            else:
                raise VETextNonRetryableException from e
```

## Engineering Checklist

- [ ] Determine which status codes should be retried when returned from `mobile/push/send` [429, 500, 502, 503, 504]
- [ ] Add retries as determined
- [ ] Remove TODO comment

## Acceptance Criteria

- [ ] If we choose to retry, we do
- [ ] If we choose to not retry, we don't
- [ ] update unit tests as needed
- [ ] functionality remains unchanged

## QA Considerations
_For QA to populate. Leave blank if QA is not applicable on this ticket._
- [ ] regression passes

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/894?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/894?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
The TODO no longer exists in this file. Closing ticket as unneeded
