### ISSUE TITLE
TODO: Update check phone number format in test_send_to_provider

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#896]
## User Story - Business Need
The codebase is littered with TODO statements. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/delivery/test_send_to_providers.py#L761) asks to update a test in `/tests/app/delivery/test_send_to_providers.py`such that a mock is used.

Don't test the actual return value of notification_utils.recipients.validate_and_format_phone_number instead, mock that dependency and check that it's used properly.

The code itself seems to indicate that this is already mocked, if it is, remove the TODO comment.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**  to remove TODO comments
**So that**  the code is more straightforward for development

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/delivery/test_send_to_providers.py#L761): Don't test the actual return value of notification_utils.recipients.validate_and_format_phone_number instead, mock that dependency and check that it's used properly
```python

def test_send_sms_to_provider_should_format_phone_number(sample_notification, mock_sms_client):
    sample_notification.to = '+1 650 253 2222'

    send_to_providers.send_sms_to_provider(sample_notification)

    # TODO: don't test the actual return value of notification_utils.recipients.validate_and_format_phone_number
    # instead, mock that dependency and check that it's used properly
    assert mock_sms_client.send_sms.call_args[1]['to'] == '+16502532222'
```

## Engineering Checklist

- [ ] Review the code in question - is this already mocked? 
- [ ] If so, remove the TODO comment.
- [ ] If not, mock it and remove the TODO comment.

## Acceptance Criteria

- [ ] The code does not test the return value of `notification_utils.recipients.validate_and_format_phone_number`, but uses a mock
- [ ] The unit test works as expected
- [ ] The TODO comment is removed

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/896?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/896?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/896?planning-poker) with Zenhub @nikolai-efimov

**Comment by cris-oddball** [comment]
The TODO no longer exists in this file. Closing ticket as unneeded.
