### ISSUE TITLE
TODO Move callback test to model instead of calling an API

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#897]
## User Story - Business Need
The codebase is littered with TODOs. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/service/test_callback_rest.py#L178) concerns moving an API call in a test for callbacks to a model, rather than making an API call.  `/test_callback_rest.py`

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** VANotify
**I want**  to use models instead of API calls in unit tests
**So that**  the function is tested adequately

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/service/test_callback_rest.py#L178): No need to test using API calls - move that test to model
```
    # TODO: No need to test using API calls - move that test to model?
    def test_create_service_callback_creates_delivery_status_with_default_statuses_if_no_statuses_passed(
            self, notify_db_session, client, sample_service
    ):
        user = sample_service.users[0]
        data = {
            "url": "https://some.service/delivery-receipt-endpoint",
            "bearer_token": "some-unique-string",
            "callback_type": DELIVERY_STATUS_CALLBACK_TYPE,
            "callback_channel": WEBHOOK_CHANNEL_TYPE
        }

        response = client.post(
            url_for('service_callback.create_service_callback', service_id=sample_service.id),
            data=json.dumps(data),
            headers=[('Content-Type', 'application/json'),
                     ('Authorization', f'Bearer {create_access_token(user)}')]
        )

        resp_json = response.json["data"]
        created_service_callback_api = get_service_callback(resp_json["id"])
        assert created_service_callback_api.notification_statuses == NOTIFICATION_STATUS_TYPES_COMPLETED
```

## Engineering Checklist

- [ ] A model is created for this test
- [ ] The test uses the model instead of making an API call
- [ ] the TODO comment is removed

## Acceptance Criteria

- [ ] The unit test works as expected after the change
- [ ] The TODO comment is removed

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/897?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/897?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/897?planning-poker) with Zenhub @nikolai-efimov

**Comment by cris-oddball** [comment]
The TODO no longer exists in this file. Closing ticket as unneeded.
