### ISSUE TITLE
TODO Test recipient_identifier by enabling feature flag in the testing environment

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#898]
## User Story - Business Need
The codebase is littered with TODOs. This TODO states that testing recipient_identifier requires an active feature flag in the test environment.

Set the feature flag to enable testing this code, add a test for recipient identifier and remove the TODO

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want**  to enable a feature flag in the test environment
**So that**  code coverage to test recipient_identifier is complete

### Additional Info and Resources

[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/v2/notifications/test_post_notifications.py#L87): Testing recipient_identifier requires an active feature flag that is not active in the testing environment.
`{"recipient_identifier": {"id_type": IdentifierType.VA_PROFILE_ID.value, "id_value": "bar"}}`

**Needs more info**

## Engineering Checklist

- [ ] Enable feature flag in test environment
- [ ] Add test for recipient identifier where the TODO comment is
- [ ] Remove the TODO comment

## Acceptance Criteria

- [ ] there exists a unit test for recipient_identifier which works
- [ ] the TODO comment is removed

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/898?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/898?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
The TODO no longer exists in this file. Closing ticket as unneeded.
