### ISSUE TITLE
TODO: Behaviour change when default communication item permissions

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#899]
## User Story - Business Need

The codebase is littered with TODO comments. This TODO note that the behavior in the test `test_should_raise_exception_if_recipient_has_no_permissions()` in  `app/va/vaprofile/va_profile_client.py` will change "once we starting using default communication item permissions"

Determine whether to just remove the TODO comment or to produce some work that addresses the changed behavior.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** to resolve issues noted in TODOs
**So that**  so that the code base is straightforward to develop against

### Additional Info and Resources
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/app/va/va_profile/test_va_profile_client.py#L702): Note that this behaviour will change once we starting using default communication item permissions
```python
def test_should_raise_exception_if_recipient_has_no_permissions(
            self, test_va_profile_client, rmock
    ):
        # TODO: Note that this behavior will change once we starting using default communication item permissions
        response = {
            "txAuditId": "37df9590-e791-4392-ae77-eaffc782276c",
            "status": "COMPLETED_SUCCESS"
        }
        rmock.get(ANY, json=response, status_code=200)

        recipient_identifier = RecipientIdentifier(id_type='VAPROFILEID', id_value='1')

        with pytest.raises(CommunicationItemNotFoundException):
            test_va_profile_client.get_is_communication_allowed(
                recipient_identifier, 'some-random-id', 'some-notification-id', SMS_TYPE
            )
```

## Engineering Checklist

- [ ] Determine if the TODO comment is relevant
- [ ] If it is, then resolve the issue as asked for in the comment
- [ ] If it is superfluous, then just delete the TODO comment

## Acceptance Criteria

- [ ] The TODO is gone
- [ ] The feature works as it is currently does, with no regressions introduced.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/899?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/899?planning-poker) with Zenhub @justaskdavidb2

**Comment by cris-oddball** [comment]
@mjones-oddball 
"this behaviour will change once we starting using default communication item permissions" -> are we using default communication item permissions currently or is this some future work?

**Comment by mjones-oddball** [comment]
@cris-oddball I'm not following this ticket. We've been using default send for communication items the entire time. Only recently was explicit consent logic added, so we now support both.

**Comment by cris-oddball** [comment]
The TODO comment in question was actually removed from the code recently (and @mjones-oddball has a point above that I missed back then that we are doing defaults sends and explicit logic). 

Not sure if we still need this ticket @k-macmillan ?

**Comment by cris-oddball** [comment]
This ticket is no longer needed, the TODO no longer exists in the file in question. Closing ticket.
