### ISSUE TITLE
TODO: parametrize the highly repetitive tests for vaprofile integration

### ISSUE THREAD

**Issue by trevor2718** [department-of-veterans-affairs/notification-api#901]
## User Story - Business Need
The codebase is littered with TODO comments. This [TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/72465e2d5313c95312707493146644579c184d8f/tests/lambda_functions/va_profile/test_va_profile_integration.py#L354) asks if certain tests in `tests/lambda_functions/va_profile/test_va_profile_integration.py`

Parametrize these tests to adhere to DRY.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a**  VANotify
**I want** to parametrize pytests tests for highly repetitive tests
**So that**  the codebase is smaller, adheres to DRY and is more maintainable

### Additional Info and Resources

tests/lambda_functions/va_profile/test_va_profile_integration.py
[TODO](https://github.com/department-of-veterans-affairs/notification-api/blob/master/tests/lambda_functions/va_profile/test_va_profile_integration.py#L354) - The next 3 test functions are highly repetitive.  Is there a way to parametrize them?

- test_va_profile_opt_in_out_lambda_handler_valid_dict
- test_va_profile_opt_in_out_lambda_handler_valid_str
- test_va_profile_opt_in_out_lambda_handler_valid_byte

## Engineering Checklist

- [ ] parametrize the above tests

## Acceptance Criteria

- [ ] The unit tests behave as before with the tests parametrized.

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/901?planning-poker) with Zenhub @EvanParish @k-macmillan @kalbfled @trevor2718 @jakehova @cris-oddball @ianperera

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/901?planning-poker) with Zenhub @justaskdavidb2

**Comment by mjones-oddball** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-api/901?planning-poker) with Zenhub @nikolai-efimov

**Comment by cris-oddball** [comment]
The TODO no longer exists in this file. Closing ticket as unneeded.
